server:
  port: 8087
  servlet:
    context-path: /library

spring:
  data:
    mongodb:
      host: localhost
      port: 27018
      database: dblibrary

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: none

logging:
  level:
    ru.otus: info
    org.springframework: info

