server:
  port: 8085
  servlet:
    context-path: /booking_notification

spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false

  mail:
    host: smtp.mail.ru
    port: 465
    username: ${email.server.user}
    password: ${email.server.password}
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

integration:
  users:
    url: http://localhost:8083/booking_users

app:
  email:
    admin-email: ${admin.email}
  sms:
    twilio-account-sid: AC6a7e417f4346adb8eceee461c195b224
    twilio-auth-token: d08fba56cb266a663e252536733618be
    twilio-phone-number: '+19183022060'

logging:
  level:
    ru.otus: debug
    org.springframework: debug
