server:
  port: 8087
  servlet:
    context-path: /library

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
    initialization-mode: always
    schema: classpath:schema.sql
    data: classpath:data.sql
    sql-script-encoding: utf-8

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true

    show-sql: true

logging:
  level:
    ru.otus: debug
    org.springframework: debug
